// Generates src/styles/icons.css from src/lib/icons.mjs.
//
// Icons ship as CSS mask-image data URIs (the same output as Iconify's Tailwind plugin,
// produced here by @iconify/utils getIconsCSS), so:
//   - no icon font / no extra request — they ride in the already-cached site CSS
//   - each use is a ~40-byte <span class="ic ic-read"> (cheap on the 4k-card browse page)
//   - they inherit `color` via background: currentColor
// Output is committed; rerun only when icons.mjs changes: `pnpm run gen:icons`.
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getIconsCSS, getIconData } from '@iconify/utils';
import { ICONS, parseIcon } from '../src/lib/icons.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, '..', 'src', 'styles', 'icons.css');

// Fetch just the icons we use, per set, from the Iconify API (avoids multi-MB icon-set packages).
const bySet = new Map();
for (const value of Object.values(ICONS)) {
  const { set, name } = parseIcon(value);
  if (!bySet.has(set)) bySet.set(set, new Set());
  bySet.get(set).add(name);
}
const sets = new Map();
for (const [set, names] of bySet) {
  const url = `https://api.iconify.design/${set}.json?icons=${[...names].join(',')}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`iconify API ${res.status} for ${url}`);
  const data = await res.json();
  if (data.not_found?.length) throw new Error(`icons not found in ${set}: ${data.not_found.join(', ')}`);
  sets.set(set, data);
}

// Build one set keyed by our semantic names so classes read .ic-read, not .ic-menu-book-outline.
// getIconData resolves aliases and merges set-level width/height into each icon.
const semantic = { prefix: 'ic', icons: {} };
for (const [key, value] of Object.entries(ICONS)) {
  const { set, name } = parseIcon(value);
  const icon = getIconData(sets.get(set), name);
  if (!icon) throw new Error(`icon ${value} missing from API response`);
  semantic.icons[key] = icon;
}

const css = getIconsCSS(semantic, Object.keys(ICONS), {
  mode: 'mask',
  commonSelector: '.ic',
  iconSelector: '.ic-{name}',
  format: 'compressed',
});

const header = `/* GENERATED by scripts/gen_icons.mjs from src/lib/icons.mjs — do not edit by hand.
 * Material Symbols (Google) and Material Design Icons (Pictogrammers), both Apache-2.0, via Iconify. */
`;
// Layout tweaks for inline use next to a text label.
const extra = `.ic{flex:0 0 auto;vertical-align:-0.14em}\n`;
writeFileSync(OUT, header + css + extra);
console.log(`wrote ${OUT}: ${Object.keys(ICONS).length} icons from ${[...sets.keys()].join(', ')}, ${css.length} bytes`);
