// Generates icon CSS from src/lib/icons.mjs:
//   src/styles/icons.css          — DEFAULT_SET, bundled into the site CSS
//   public/icons/<set>.css        — each other set, as [data-icons=<set>] overrides
//                                   (multicolour icons as background images, not masks),
//                                   fetched only when a visitor picks it in the footer
//
// Icons ship as CSS mask-image data URIs (the same output as Iconify's Tailwind plugin,
// produced here by @iconify/utils), so:
//   - no icon font / no extra request — they ride in the already-cached site CSS
//   - each use is a ~40-byte <span class="ic ic-read"> (cheap on the 4k-card browse page)
//   - they inherit `color` via background: currentColor
// Output is committed; rerun only when icons.mjs changes: `pnpm run gen:icons`.
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getIconsCSS, getIconData, iconToSVG, iconToHTML, svgToURL } from '@iconify/utils';
import { DEFAULT_SET, ICON_SETS, parseIcon } from '../src/lib/icons.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const KEYS = Object.keys(ICON_SETS[DEFAULT_SET].icons);

for (const [id, { icons }] of Object.entries(ICON_SETS)) {
  const missing = KEYS.filter((k) => !icons[k]);
  if (missing.length) throw new Error(`icon set ${id} is missing: ${missing.join(', ')}`);
}

// Fetch just the icons we use, per Iconify set, from the Iconify API (avoids multi-MB
// icon-set packages).
const wanted = new Map();
for (const [id, { icons }] of Object.entries(ICON_SETS)) {
  for (const value of Object.values(icons)) {
    const { set, name } = parseIcon(value, id);
    if (!wanted.has(set)) wanted.set(set, new Set());
    wanted.get(set).add(name);
  }
}
const fetched = new Map();
for (const [set, names] of wanted) {
  const url = `https://api.iconify.design/${set}.json?icons=${[...names].join(',')}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`iconify API ${res.status} for ${url}`);
  const data = await res.json();
  if (data.not_found?.length) throw new Error(`icons not found in ${set}: ${data.not_found.join(', ')}`);
  fetched.set(set, data);
}

// One Iconify set keyed by our semantic names so classes read .ic-read, not .ic-menu-book-outline.
// getIconData resolves aliases and merges set-level width/height into each icon.
function semanticSet(id) {
  const out = { prefix: 'ic', icons: {} };
  for (const [key, value] of Object.entries(ICON_SETS[id].icons)) {
    const { set, name } = parseIcon(value, id);
    const icon = getIconData(fetched.get(set), name);
    if (!icon) throw new Error(`icon ${set}:${name} missing from API response`);
    out.icons[key] = icon;
  }
  return out;
}

function sourcesOf(id) {
  const sets = new Set(Object.values(ICON_SETS[id].icons).map((v) => parseIcon(v, id).set));
  return [...sets].join(', ');
}

const header = (id) => `/* GENERATED by scripts/gen_icons.mjs from src/lib/icons.mjs — do not edit by hand.
 * ${ICON_SETS[id].label} icons via Iconify (${sourcesOf(id)}). */
`;

// Default set: full rules, including the shared .ic mask rule.
{
  const css = getIconsCSS(semanticSet(DEFAULT_SET), KEYS, {
    mode: 'mask',
    commonSelector: '.ic',
    iconSelector: '.ic-{name}',
    format: 'compressed',
  });
  // Layout tweaks for inline use next to a text label.
  const extra = `.ic{flex:0 0 auto;vertical-align:-0.14em}\n`;
  const out = path.join(ROOT, 'src', 'styles', 'icons.css');
  writeFileSync(out, header(DEFAULT_SET) + css + extra);
  console.log(`wrote ${out}: ${KEYS.length} icons, ${css.length} bytes`);
}

// Other sets: only swap --svg, scoped to the <html data-icons> switch.
for (const id of Object.keys(ICON_SETS)) {
  if (id === DEFAULT_SET) continue;
  const { icons } = semanticSet(id);
  let css = '';
  for (const key of KEYS) {
    const svg = iconToSVG(icons[key]);
    // Same rule Iconify uses: a currentColor icon is a mask tinted by the text colour;
    // anything else (multicolour) is drawn as-is as a background image.
    const mono = svg.body.includes('currentColor');
    // A mask only reads alpha, and currentColor inside a data-URI image is undefined.
    const body = mono ? svg.body.replace(/currentColor/g, 'black') : svg.body;
    const url = svgToURL(iconToHTML(body, { ...svg.attributes, width: '24', height: '24' }));
    const rule = mono
      ? `--svg:${url}`
      : `--svg:${url};background:var(--svg) 0 0/100% 100% no-repeat;-webkit-mask:none;mask:none`;
    css += `[data-icons=${id}] .ic-${key}{${rule}}
`;
  }
  const dir = path.join(ROOT, 'public', 'icons');
  mkdirSync(dir, { recursive: true });
  const out = path.join(dir, `${id}.css`);
  writeFileSync(out, header(id) + css);
  console.log(`wrote ${out}: ${KEYS.length} icons, ${css.length} bytes`);
}
